[package]
name = "same-code-different-performance"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
criterion = { verson = "0.5.1", optional = true }
paste = "1.0.14"

[features]
criterion = ["dep:criterion"]
align = []
